### PR TITLE
Removed duplicate unit tests

### PR DESCRIPTION
**Pull request by smarshy**
Updated changes as per [339](https://github.com/systers/vms/pull/339)

### CODE REVIEW

**Comment by tapasweni-pathak** [comment]
@smarshy While merging this I saw we have .travis.yml in [this](https://github.com/systers/automated-testing/blob/develop/PortalVMSTests/.travis.yml) repository. Jayesh has added it, is it? 

It is better to remove it and keep only the tests in this repository.

**Comment by smarshy** [comment]
@tapasweni-pathak No, I had updated the script some time back. I will remove it

**Comment by tapasweni-pathak** [comment]
@smarshy Yes, you updated it. But did Jayesh add this in the last term?

**Comment by tapasweni-pathak** [comment]
I checked he [added](https://github.com/systers/automated-testing/commit/be59112248f450438ca00c64e562ca2c2b8d24e0). I don't see any use to have it here. Go ahead and remove it.

**Comment by smarshy** [comment]
Yes, initially he did add it

**Pull request merged**
