### PR TITLE
Updated tests after syncing

### PR DESCRIPTION
**Pull request by smarshy**
This PR contains updated automated tests for vms. All errors have been resolved after syncing previously written tests with the latest vms codebase.

### CODE REVIEW

**Comment by tapasweni-pathak** [comment]
@smarshy We have 8 failures and 1 error after this too, right?

**Comment by smarshy** [comment]
@tapasweni-pathak  Yes, we do.

**Comment by tapasweni-pathak** [comment]
> I was thinking that once the changes are merged for vms for travis, and everything is passing

@smarshy Everything will not pass until we fix the related issues. For the time being we have pulled the failing test cases out of our set. Isn't it?

**Comment by tapasweni-pathak** [comment]
As discussed this has 150 test cases with 8 failures and 1 error.

**Pull request merged**
